name: Build greeter
on: pull_request 

jobs: 
    build-greeter:
        runs-on : ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with: 
                submodules: true
            - uses: seanmiddleditch/gha-setup-ninja@master
            - run: |
                mkdir build && cd build
                cmake .. -GNinja
                cmake --build . --target all


