name: Build greeter
on: pull_request 

jobs: 
    build-greeter:
        runs-on : ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with: 
                submodules: true
            - uses: seanmiddleditch/gha-setup-ninja@master
            - run: |
                mkdir build && cd build
                cmake .. -GNinja
                cmake --build . --target all
                ls -lah 

            - uses: actions/upload-artifact@master
              with:
                name: binary-artifact
                path: build/greeter

    test-binary:
        needs: build-greeter
        runs-on : ubuntu-latest        
        steps:
            - uses: actions/download-artifact@master
              with:
                name: binary-artifact
                path: .
            - run: |
                chmod +x ./greeter
                ls -lah 
                ./greeter --version
    
